version: '3.8'

services:
  db:
    image: mysql:8.2
    container_name: mysql-sem-project
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: nodejs-app
    ports:
      - "8000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: sem_project
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

volumes:
  db_data:
